tasks:
  - name: nodemon
    init: npm install nodemon --save-dev -g 
  - name: eslint
    init: npm install eslint --save-dev
  - name: deps
    init: npm install
    command: npm start

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - humao.rest-client
