services:
  db:
    environment:
      POSTGRES_USER: feira
      POSTGRES_PASSWORD_FILE: /run/secrets/db
    image: postgres
    restart: always
    secrets:
      - db
    volumes:
      - ./db/data:/var/lib/postgresql/data
  rest-api:
    command: "npm start"
    depends_on:
      - db
    image: node
    restart: always
    user: "node"
    volumes:
      - ./rest-api:/home/node/app
    working_dir: /home/node/app
  adcipt20242-n-k-corporeichom-Misterios-do-amor-:
    command: "npm start"
    environment:
      - PORT=3000
    image: node
    restart: always
    user: "node"
    volumes:
      - ./jogos/adcipt20242-n-k-corporeichom-Misterios-do-amor-:/home/node/app
    working_dir: /home/node/app
  http-proxy:
    depends_on:
      - rest-api
    image: nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./http-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/privkey.pem:/etc/nginx/privkey.pem:ro
      - ./frontend:/frontend:ro
      - ./jogos/adcieqipt20241-huntersofancientbeasts-jogo:/jogos/adcieqipt20241-huntersofancientbeasts-jogo:ro
      - ./jogos/adcieqipt20241-Karolzinha-e-Loulou-avadakedavra:/jogos/adcieqipt20241-Karolzinha-e-Loulou-avadakedavra:ro
      - ./jogos/adcieqipt20241-nlentertainment-jogo:/jogos/adcieqipt20241-nlentertainment-jogo:ro
      - ./jogos/adcieqipt20241-Thuthu-e-Aninha-jogo:/jogos/adcieqipt20241-Thuthu-e-Aninha-jogo:ro
      - ./jogos/adcieqipt20241-vimdoalegrete-jogo:/jogos/adcieqipt20241-vimdoalegrete-jogo:ro
      - ./jogos/adcieqipt20241-vitorhlmm-Jogo:/jogos/adcieqipt20241-vitorhlmm-Jogo:ro
  redis:
    command: "redis-server --save 60 1 --loglevel warning"
    image: redis
    network_mode: host
    restart: always
    volumes:
      - ./redis/data:/data
  stun:
    depends_on:
      - redis
    environment:
      DETECT_EXTERNAL_IP: yes
      DETECT_EXTERNAL_IPV6: yes
    image: coturn/coturn
    network_mode: host
    volumes:
      - ./stun/coturn.conf:/etc/turnserver.conf:ro
secrets:
  db:
    file: secret-db
