apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsdb-data
  namespace: feira-de-jogos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard  # ajuste conforme seu cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: feira-de-jogos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: feira-de-jogos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard
