services:
  mqtt-broker:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
  db:
    environment:
      POSTGRES_USER: feira
      POSTGRES_PASSWORD_FILE: /run/secrets/db
    image: postgres
    restart: always
    secrets:
      - db
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
  rest-api:
    command: "npm start"
    depends_on:
      - db
    image: node
    restart: always
    user: "node"
    volumes:
      - ./rest-api:/home/node/app:ro
    working_dir: /home/node/app
  http-proxy:
    depends_on:
      - mqtt-broker
      - rest-api
    image: nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/privkey.pem:/etc/nginx/privkey.pem:ro
      - ./frontend:/frontend:ro
      - ./jogos:/jogos:ro
      - ./http-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  redis:
    command: "redis-server --save 60 1 --loglevel warning"
    image: redis
    network_mode: host
    restart: always
    volumes:
      - ./redis/data:/data:rw
  stun:
    depends_on:
      - redis
    environment:
      DETECT_EXTERNAL_IP: yes
      DETECT_EXTERNAL_IPV6: yes
    image: coturn/coturn
    network_mode: host
    volumes:
      - ./stun/coturn.conf:/etc/turnserver.conf:ro
secrets:
  db:
    file: secret-db
