services:
  db:
    environment:
      POSTGRES_USER: feira
      POSTGRES_PASSWORD_FILE: /run/secrets/db
    image: postgres
    restart: always
    secrets:
      - db
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
  tsdb:
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/tsdb-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/tsdb-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/tsdb-admin-token
      DOCKER_INFLUXDB_INIT_ORG: em
      DOCKER_INFLUXDB_INIT_BUCKET: em
    image: influxdb:2
    restart: always
    secrets:
      - tsdb-username
      - tsdb-password
      - tsdb-admin-token
    volumes:
      - ./tsdb/data:/var/lib/influxdb2:rw
  mqtt-broker:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    depends_on:
      - tsdb
    environment:
      GF_SERVER_DOMAIN: feira-de-jogos.dev.br
      GF_SERVER_ROOT_URL: https://feira-de-jogos.dev.br/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: true
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
  rest-api:
    command: "npm start"
    depends_on:
      - db
    image: node
    restart: always
    user: "node"
    volumes:
      - ./rest-api:/home/node/app:ro
    working_dir: /home/node/app
  http-proxy:
    depends_on:
      - mqtt-broker
      - grafana
      - rest-api
    image: nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/privkey.pem:/etc/nginx/privkey.pem:ro
      - ./frontend:/frontend:ro
      - ./jogos:/jogos:ro
      - ./http-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  redis:
    command: "redis-server --save 60 1 --loglevel warning"
    image: redis
    network_mode: host
    restart: always
    volumes:
      - ./redis/data:/data:rw
  stun:
    depends_on:
      - redis
    environment:
      DETECT_EXTERNAL_IP: yes
      DETECT_EXTERNAL_IPV6: yes
    image: coturn/coturn
    network_mode: host
    volumes:
      - ./stun/coturn.conf:/etc/turnserver.conf:ro
secrets:
  tsdb-username:
    file: secret-tsdb-username
  tsdb-password:
    file: secret-tsdb-password
  tsdb-admin-token:
    file: secret-tsdb-admin-token
  db:
    file: secret-db
