// Choose a cache name
const cacheName = 'cache-v1'

// List the files to precache
const precacheResources = [
  './',
  './assets/background',
  './assets/background/1.png',
  './assets/background/10.png',
  './assets/background/2.png',
  './assets/background/3.png',
  './assets/background/4.png',
  './assets/background/7.png',
  './assets/background/8.png',
  './assets/background/9.png',
  './assets/decoracao/bonfire.png',
  './assets/decoracao/coroa.png',
  './assets/decoracao/fg1.png',
  './assets/decoracao/fg2.png',
  './assets/decoracao/skeleton.png',
  './assets/decoracao/torch.png',
  './assets/entities/kingone.png',
  './assets/entities/kingtwo.png',
  './assets/entities/raven_fly.png',
  './assets/entities/raven_idle.png',
  './assets/final.png',
  './assets/finalTriste.png',
  './assets/fundo.png',
  './assets/iniciar.mp3',
  './assets/logo/icons8-torre-64.png',
  './assets/logo/icons8-torre-pastel-color-32.png',
  './assets/logo/icons8-torre-pastel-color-72.png',
  './assets/logo/icons8-torre-pastel-color-96.png',
  './assets/mapa.mp3',
  './assets/mapa/auto_tile_layout.png',
  './assets/mapa/castle_stones.png',
  './assets/mapa/map.png',
  './assets/mapa/mapa.json',
  './assets/mapa/mapteste.json',
  './assets/particles/jump_particle.png',
  './assets/particles/rain0.png',
  './assets/particles/rain1.png',
  './assets/particles/rain2.png',
  './assets/particles/rain3.png',
  './assets/particles/rainall.png',
  './assets/play.png',
  './assets/ui/baixo.png',
  './assets/ui/direita.png',
  './assets/ui/esquerda.png',
  './assets/ui/jump.png',
  './assets/ui/progress.png',
  './index.html',
  './index.js',
  './manifest.json',
  './style.css',
  './sw.js',
  './viqueti',
  './viqueti/exemplo',
  './viqueti/exemplo/TX Chest Animation.png',
  './viqueti/exemplo/TX FX Flame.png',
  './viqueti/exemplo/TX FX Torch Flame.png',
  './viqueti/exemplo/TX Tileset Ground.png',
  './viqueti/exemplo/TX Village Props.png',
  './viqueti/exemplo/trees',
  './viqueti/exemplo/trees/apple.png',
  './viqueti/exemplo/trees/ashberry.png',
  './viqueti/exemplo/trees/baobab.png',
  './viqueti/exemplo/trees/beech.png',
  './viqueti/exemplo/trees/birch.png',
  './viqueti/exemplo/trees/cedar.png',
  './viqueti/exemplo/trees/coconut palm.png',
  './viqueti/exemplo/trees/coffee tree.png',
  './viqueti/exemplo/trees/cypress.png',
  './viqueti/exemplo/trees/dead tree.png',
  './viqueti/exemplo/trees/limon.png',
  './viqueti/exemplo/trees/linden.png',
  './viqueti/exemplo/trees/mangrove.png',
  './viqueti/exemplo/trees/maple.png',
  './viqueti/exemplo/trees/oak.png',
  './viqueti/exemplo/trees/palm.png',
  './viqueti/exemplo/trees/pine.png',
  './viqueti/exemplo/trees/poplar.png',
  './viqueti/exemplo/trees/sakura.png',
  './viqueti/exemplo/trees/sea-buckthorn.png',
  './viqueti/exemplo/trees/spruce.png',
  './viqueti/exemplo/trees/trees.png',
  './viqueti/exemplo/trees/treesnames.png',
  './viqueti/exemplo/trees/willow.png',
  './viqueti/exemplo/txt.txt',
  './viqueti/exemploss',
  './viqueti/exemploss/1.png',
  './viqueti/exemploss/10.png',
  './viqueti/exemploss/11.png',
  './viqueti/exemploss/12.png',
  './viqueti/exemploss/13.png',
  './viqueti/exemploss/14.png',
  './viqueti/exemploss/15.png',
  './viqueti/exemploss/16.png',
  './viqueti/exemploss/17.png',
  './viqueti/exemploss/2.png',
  './viqueti/exemploss/3.png',
  './viqueti/exemploss/4.png',
  './viqueti/exemploss/5.png',
  './viqueti/exemploss/6.png',
  './viqueti/exemploss/7.png',
  './viqueti/exemploss/8.png',
  './viqueti/exemploss/9.png',
  './viqueti/exemploss/teste.txt'
]

self.addEventListener('install', (event) => {
  console.log('Service worker install event!')
  event.waitUntil(caches.open(cacheName).then((cache) => cache.addAll(precacheResources)))
})

self.addEventListener('activate', (event) => {
  console.log('Service worker activate event!')
})

self.addEventListener('fetch', function (event) {
  event.respondWith(
    caches.match(event.request).then(function (response) {
      return response || fetch(event.request)
    })
  )
})