server {
  listen [::]:8080 ipv6only=off;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  gzip_static on;

  location / {
    try_files $uri $uri/ =404;

    # Retirado de: https://docs.unity3d.com/Manual/webgl-server-configuration-code-samples.html
    location ~ .+\.(data|symbols\.json)\.br$ {
      gzip off;
      add_header Content-Encoding br;
      default_type application/octet-stream;
    }

    location ~ .+\.js\.br$ {
      gzip off;
      add_header Content-Encoding br;
      default_type application/javascript;
    }

    location ~ .+\.wasm\.br$ {
      gzip off;
      add_header Content-Encoding br;
      default_type application/wasm;
    }

    location ~ .+\.(data|symbols\.json)\.gz$ {
      gzip off;
      add_header Content-Encoding gzip;
      default_type application/gzip;
    }

    location ~ .+\.js\.gz$ {
      gzip off;
      add_header Content-Encoding gzip;
      default_type application/javascript;
    }

    location ~ .+\.wasm\.gz$ {
      gzip off;
      add_header Content-Encoding gzip;
      default_type application/wasm;
    }
  }
}