server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  gzip_static on;

  location / {
    try_files $uri $uri/ =404;
  }

  location ~ \.js\.gz$ {
      gzip_static on;
      types { application/javascript js; }
      add_header Content-Encoding gzip;
  }
 
  location ~ \.wasm\.gz$ {
      gzip_static on;
      types { application/wasm wasm; }
      add_header Content-Encoding gzip;
  }
 
  location ~ \.data\.gz$ {
      gzip_static on;
      types { application/octet-stream; }
      add_header Content-Encoding gzip;
  }
}