name: Build with Parcel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Parcel
        run: npx parcel build src/index.html

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: parcel-build
          path: dist/
          retention-days: 7